add new comment
venturars/isdi-parttime-202406 pull request #12
Opened 2024-06-27 19:36 UTC by Rodrigoregomedeiros

2024-06-27 19:37 UTC, angelabernaldz approved these changes

2024-07-02 18:25 UTC, angelabernaldz commented
Puedes cambiar el titulo a First PR, porfa?

2024-07-02 18:25 UTC, venturars requested changes
Esta PR no puede asar así

2024-07-02 18:25 UTC, angelabernaldz requested changes
Falta por cambiar el titulo y estaria listo

2024-07-02 18:28 UTC, Rodrigoregomedeiros commented
Ya lo he cambiado!

2024-07-02 18:29 UTC, angelabernaldz approved these changes

2024-07-02 18:30 UTC, venturars approved these changes
molt be!

2024-07-02 18:30 UTC, merged