Develop branch
venturars/isdi-parttime-202406 pull request #9
Opened 2024-06-27 19:21 UTC by LeideVanessaC

add comment line and creating Branch develop

2024-06-27 19:45 UTC, Rafa0297 approved these changes

2024-07-02 18:21 UTC, Rafa0297 commented
Hola Leide, hay que cambiar el titulo a 'First PR'

2024-07-02 18:23 UTC, Rafa0297 requested changes
Cambio en el titulo

2024-07-03 12:17 UTC, LeideVanessaC commented
> Hola Leide, hay que cambiar el titulo a 'First PR'

the title corrected.

2024-07-03 13:22 UTC, Rafa0297 approved these changes

2024-07-03 17:21 UTC, venturars approved these changes
molt be

2024-07-03 17:21 UTC, merged